#pragma once

/* This is a workaround. The header file generated by FLEX is completely broken so we manually maintain one instead */

#include <stdio.h>

struct sfgsym_expr_parser;
typedef void* sfgsymscan_t;

typedef struct yy_buffer_state* YY_BUFFER_STATE;
typedef union SFGSYMSTYPE SFGSYMSTYPE;
typedef struct SFGSYMLTYPE SFGSYMLTYPE;

int sfgsymlex_init_extra(struct sfgsym_expr_parser* driver, sfgsymscan_t* ptr_yy_globals);
int sfgsymlex_destroy(sfgsymscan_t yyscanner);
YY_BUFFER_STATE sfgsym_scan_bytes(const char *bytes, int len , sfgsymscan_t scanner);
void sfgsym_delete_buffer(YY_BUFFER_STATE b , sfgsymscan_t scanner);
int sfgsymlex(SFGSYMSTYPE* sfgsymlval_param, SFGSYMLTYPE* yylloc_param, sfgsymscan_t scanner);
struct sfgsym_expr_parser* sfgsymget_extra(sfgsymscan_t scanner);
